/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmRouteImport } from './routes/dm'
import { Route as GmRouteImport } from './routes/gm'
import { Route as GmIndexRouteImport } from './routes/gm.index'
import { Route as GmReportsRouteImport } from './routes/gm.reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmRoute = DmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const GmIndexRoute = GmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GmRoute,
} as any)
const GmReportsRoute = GmReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dm': typeof DmRoute
  '/gm': typeof GmRouteWithChildren
  '/gm/reports': typeof GmReportsRoute
  '/gm/': typeof GmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dm': typeof DmRoute
  '/gm/reports': typeof GmReportsRoute
  '/gm': typeof GmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dm': typeof DmRoute
  '/gm': typeof GmRouteWithChildren
  '/gm/reports': typeof GmReportsRoute
  '/gm/': typeof GmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dm' | '/gm' | '/gm/reports' | '/gm/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dm' | '/gm/reports' | '/gm'
  id: '__root__' | '/' | '/dm' | '/gm' | '/gm/reports' | '/gm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DmRoute: typeof DmRoute
  GmRoute: typeof GmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dm': {
      id: '/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof DmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm/': {
      id: '/gm/'
      path: '/'
      fullPath: '/gm/'
      preLoaderRoute: typeof GmIndexRouteImport
      parentRoute: typeof GmRoute
    }
    '/gm/reports': {
      id: '/gm/reports'
      path: '/reports'
      fullPath: '/gm/reports'
      preLoaderRoute: typeof GmReportsRouteImport
      parentRoute: typeof GmRoute
    }
  }
}

interface GmRouteChildren {
  GmReportsRoute: typeof GmReportsRoute
  GmIndexRoute: typeof GmIndexRoute
}

const GmRouteChildren: GmRouteChildren = {
  GmReportsRoute: GmReportsRoute,
  GmIndexRoute: GmIndexRoute,
}

const GmRouteWithChildren = GmRoute._addFileChildren(GmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DmRoute: DmRoute,
  GmRoute: GmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
